Add incoming message support, add dependency on sms
dpi/sms_twilio pull request #2
Opened 2016-10-16 16:03 UTC by bradjones1

There's a missing dependency on sms framework in the info file, and also I've added support for parsing incoming messages. I have asked on this issue what the "official" DX workflow is for handling incoming messages, but from the documentation I can find and the existing code, it looks like we at least need to handle the interface I've implemented here. Also included some helper functions to process and verify the message from Twilio against the signature.

2016-10-16 16:07 UTC, bradjones1 commented
In reading your other issues on Drupal.org, it looks like excluding the sms dependency might have been purposeful, however I'm not sure how helpful that is considering the Plugin we provide here meets the annotation defined in smsframework? I would imagine 99% of people will be using that plugin, and assuming it gets provided by another module seems like a bit of a namespace collision? Regardless, the main thrust here is the incoming message parsing. :-)

2016-10-16 16:41 UTC, dpi commented
The non dependency on SMS Framework is intentional. Both because it technically is not a dependency, it is an optional dependency, and because this module is a proposed alternative to the [Twilio](https://drupal.org/project/twilio) project. Which does not have a dependency on the framework.

> namespace collision

If it turns out this module needs to be fully supported, then the namespace can change.

2016-10-16 16:44 UTC, bradjones1 commented
@dpi OK on the dependency piece, what do you think of the incoming message parsing component?

2016-10-16 16:49 UTC, dpi commented
I have responded in [DX: Documentation for incoming message workflow](https://www.drupal.org/node/2816823).

2016-10-16 16:52 UTC, bradjones1 commented
@dpi Thanks, that's pretty much exactly what I've done in my application, paired with the changes here. Let me know if you think you can accept that part of the PR?

2016-10-16 17:03 UTC, dpi commented
The new methods on the plugin dont seem to be required for operation of the plugin itself.

Perhaps `buildIncomingFromRequest` could be static /or/ made as a controller responding to the incoming SMS route.

2016-10-16 17:07 UTC, dpi commented
At this point I'm not going to add SMS Framework as a dependency.

I'll allow Composer's [suggest](https://getcomposer.org/doc/04-schema.md#suggest) if it works with Drupal infrastructure.

2016-10-16 17:08 UTC, bradjones1 commented
I considered making buildIncomingFromRequest and friends static, however the validation of the POST from Twilio requires knowing the account key, since that's what the signature is based on, which in turn requires having the plugin configuration to get the settings. So the idea is that the controller receiving the request would instantiate the plugin and then call that method. But yes, that was my first thought until it turned out there wasn't sufficient data to do the job without context.

E.g.:
```php
// Snippets from controller class ...
  public function __construct(RequestStack $request_stack, SmsProviderInterface $sms) {
    $this->request_stack = $request_stack;
    $this->sms = $sms;
    $this->setPlugin();
  }

  private function setPlugin() {
    $gateway = $this->entityTypeManager()
      ->getStorage('sms_gateway')
      ->loadByProperties(['id' => 'twilio']);
    $gateway = reset($gateway);
    $this->gateway = $gateway;
    $this->plugin = $this->gateway->getPlugin();
  }

  public function process() {
    try {
      $sms = $this->plugin->buildIncomingFromRequest($this->request_stack->getCurrentRequest());
      $sms->setGateway($this->gateway);
    }
    catch (\Throwable $e) {
      throw $e;
    }
    $messages = $this->sms->incoming($sms);
    // Since multiple messages might have been considered received, send replies
    // in separate new calls.
    return new Response();
  }
```

2016-10-16 17:12 UTC, dpi commented
Easiest solution: You could add the plugin ID as a slug to the route. (mysite.com/sms_twilio/$mypluginid/somethingrandomandobscure

The SMS Framework incoming pushed reports system is what I would be this on. The route is just a random string. We embed the plugin ID (the context) into the route definition itself (See `\Drupal\sms\Routing\RouteSubscriber::routes`), so when the controller is executed we can use the route matcher service and get the context from that.

2016-10-16 17:14 UTC, dpi commented
edited above

2016-10-16 17:16 UTC, bradjones1 commented
@dpi Thanks. Are you suggesting that you would rather those helper functions be static, and take the key to compare the signature against as an argument, rather than instantiating the plugin?

2016-10-16 17:18 UTC, dpi commented
Create a new controller class to respond to the route, then load the plugin instance with SmsGatewayPluginManager

2016-10-16 17:20 UTC, bradjones1 commented
@dpi Right, that's what the above code snippet is doing. But you objected earlier to having `buildIncomingFromRequest` as a method on the plugin?

> The new methods on the plugin dont seem to be required for operation of the plugin itself.

I'm suggesting that it should be a method on the plugin because the validation requires the plugin configuration. Sorry if there's miscommunication on this, I appreciate the feedback.

2016-10-16 17:22 UTC, dpi commented
I think move buildIncomingFromRequest to a new controller, then load the plugin instance. You can get the configuration with plugin::getConfiguration.

2016-10-16 17:24 UTC, bradjones1 commented
@dpi Any thoughts on keeping the validate() function as static, then, since that's basically just a wrapper function around the library and rather unlikely to be different between implementations?

2016-10-16 17:24 UTC, bradjones1 commented
Or, making a utility class with that function in it? Seems helpful to provide, one way or the other.

2016-10-17 11:46 UTC, dpi commented
If the utility does not have logic specific to SMS Framework then I would not include it in the existing gateway plugin. A utility class or service should work.

2016-10-17 11:48 UTC, dpi commented
I originally created this module in the span of about 2-3 hours, so I'm not familiar with the incoming SMS API's.

Can you paste URLs you consider relevant to reviewing this PR.

2016-10-17 13:53 UTC, dpi requested changes
needs work

2016-10-17 13:53 UTC, dpi commented on sms_twilio.info.yml
> +  - smsframework:sms
Will not merge this, see Composer' 'suggest'.

2016-10-17 13:53 UTC, dpi commented on src/Plugin/SmsGateway/Twilio.php
> +  private function validate(Request $request) {
generally we prefer protected visibility

2016-10-17 13:53 UTC, dpi commented on src/Plugin/SmsGateway/Twilio.php
> +  /**
This entire chunk can be moved to a separate route controller.

2016-10-17 13:53 UTC, dpi commented on src/Plugin/SmsGateway/Twilio.php
> +  public function incoming(SmsMessageInterface $sms_message) {
We dont need to use the incoming method

2016-10-18 01:16 UTC, bradjones1 commented on src/Plugin/SmsGateway/Twilio.php
> +  public function incoming(SmsMessageInterface $sms_message) {
It's required for the Plugin to implement `SmsGatewayPluginIncomingInterface`. The logic provided is pretty basic and I'm adding a test on the data being stored in the "data" option for setting the status... but we have to implement it on the plugin. SMS module tests for that interface being implemented to determine if the plugin can handle incoming SMS.

2016-10-18 06:57 UTC, bradjones1 commented
@dpi Made a number of changes based on your feedback.

2017-02-01 00:13 UTC, bradjones1 commented on src/Plugin/SmsGateway/Twilio.php
> +  /**
I think this might be outdated review given the API changes in smsframework that expect certain functionality on the plugin.

2017-02-01 00:14 UTC, bradjones1 commented
@dpi can you take a fresh look at this given the changes in https://www.drupal.org/node/2832601 ?

2017-02-01 03:14 UTC, dpi commented
I believe @clrockwell79 is already working on changes.

2017-02-01 03:16 UTC, clrockwell79 commented
Sorry - I do have the incoming working locally.  I'm going to review @bradjones1 PR and I'll do what I can to get the incoming into the dev branch before weeks end.

2017-02-02 03:10 UTC, dpi requested changes
general coding review. 
implementation with twilio api not considered.

2017-02-02 03:10 UTC, dpi commented on src/Plugin/SmsGateway/Twilio.php
> +    $result->setReports([$report]);
`setReports` can be cleaned up a lot by using `addReport` instead. See https://www.drupal.org/node/2836114

2017-02-02 03:10 UTC, dpi commented on src/Plugin/SmsGateway/Twilio.php
> +   * @param \Symfony\Component\HttpFoundation\Request $request
missing documentation for `@param`

2017-02-02 03:10 UTC, dpi commented on src/Plugin/SmsGateway/Twilio.php
> +   * @return \Drupal\sms\Message\SmsMessage
Use SmsMessageInterface for return type,  missing documentation for `@return`

2017-02-02 03:10 UTC, dpi commented on src/Plugin/SmsGateway/Twilio.php
> +   * @param \Symfony\Component\HttpFoundation\Request $request
missing documentation for `@param`

2017-02-02 03:10 UTC, dpi commented on src/Plugin/SmsGateway/Twilio.php
> +   * @param \Drupal\sms\Entity\SmsGatewayInterface $gateway
missing documentation for `@param`

2017-02-02 03:10 UTC, dpi commented on src/Plugin/SmsGateway/Twilio.php
> +   * @return \Drupal\sms\SmsProcessingResponse
missing documentation for `@return`

2017-02-02 03:10 UTC, dpi commented on src/SmsUtility.php
> +   * @param \Drupal\sms_twilio\Plugin\SmsGateway\Twilio $plugin
missing docs for `@param`

2017-02-02 03:10 UTC, dpi commented on src/SmsUtility.php
>     * @throws \Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException
missing docs for `@throws`

2017-02-02 03:10 UTC, dpi commented on src/SmsUtility.php
> +  public static function validate(Request $request, Twilio $plugin) {
No return type? Shouldnt this return TRUE on success?

2017-02-02 03:10 UTC, dpi commented on src/SmsUtility.php
>     * @return array An array of files, with url and content-type keys.
missing docs for `@return`

2017-02-02 03:10 UTC, dpi commented on src/SmsUtility.php
>     * @param array $params The original payload from Twilio.
missing docs for `@param`

2017-02-02 03:10 UTC, dpi commented on src/SmsUtility.php
>   * Class SmsUtility
Class description needs expansion.

2017-02-02 03:18 UTC, dpi requested changes

2017-02-02 03:18 UTC, dpi commented on composer.json
> +    "drupal/smsframework": "Provides the SmsGateway Plugin annotation."
Description could be simplified to 'Provides integration with SMS Framework'

2017-02-02 03:18 UTC, dpi commented on src/Plugin/SmsGateway/Twilio.php
> +  public function incoming(SmsMessageInterface $sms_message) {
remove this method wholesale. (old api)

2017-02-02 03:25 UTC, clrockwell79 commented
I spent some time merging my work with @bradjones1 and I think the major things were addressed by that process (no return on validate, incoming is deprecated).

I too used setReports so I'll look into addReports.  The documentation stuff still needs to be cleaned up.  I'm going to upload my patch to the d.o issue.

2017-02-02 03:50 UTC, bradjones1 commented
Thanks to you both. I'll pull in the patch from the [d.o. issue](https://www.drupal.org/node/2829760) tomorrow morning and update this PR, since it makes things way easier to visualize than drupal.org, IMHO. Appreciate the cooperation and feedback.

2017-02-02 21:54 UTC, bradjones1 commented
Merged the patch from d.o., included some of the code style changes... it's slightly different from the patch, which was for instance missing the route-generation annotations, but mostly brought over as-is.

2017-02-04 17:35 UTC, dpi commented on src/Utility/TwilioValidation.php
> +  public static function validateIncoming(Request $request, ConfigurablePluginInterface $sms_gateway) {
what happened here?

2017-02-04 17:36 UTC, dpi commented on src/Plugin/SmsGateway/Twilio.php
> +    $report->setRecipient($recipient);
this change should be prioritized in a different PR.

2017-02-04 17:36 UTC, dpi approved these changes

2017-02-04 17:37 UTC, dpi commented on src/Utility/TwilioValidation.php
> +  public static function validateIncoming(Request $request, ConfigurablePluginInterface $sms_gateway) {
deleted

2017-02-05 16:22 UTC, merged